config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root 'dashboard#show'
    resource :session, only: [:new, :create, :destroy]
    resources :registrations, only: [:index, :edit, :update, :destroy]
    resources :people, only: [:index]
  end
  
  root 'registrations#new'
  resources :registrations, only: [:new, :create, :show]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/views/layouts/admin.html.erb
<% content_for :head do %>
    <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
<% end %>

<% if signed_in? %>
    <% content_for :header do %>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <%= link_to 'Admin', admin_root_path, class: 'navbar-brand' %>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><%= link_to 'Anmälningar', admin_registrations_path %></li>
                        <li><%= link_to 'Deltagare', admin_people_path %></li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
    <% end %>
<% end %>

<% content_for :content do %>
    <%= yield %>
<% end %>

<%= render template: "layouts/application" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title><%= yield(:title) %> &raquo; Furulundskyrkans gemenskapshelg</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <%= yield :head %>
  </head>
  <body>
    <%= yield :header %>

    <div class="container">
      <%= content_for?(:content) ? yield(:content) : yield %>
    </div>
  </body>
</html>

app/views/layouts/registration.html.erb
<% content_for :head do %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
<% end %>

<% content_for :header do %>
    <div class="header">
        <%= image_tag("banner.png", alt: "Furulundskyrkans och Öjersjökyrkans församlingsläger", class: "center-block img-responsive") %>     
    </div>
<% end %>

<% content_for :content do %>
    <%= yield %>
<% end %>

<%= render template: "layouts/application" %>